spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/task
    username: root
    password: root
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8083
  
#Eureka
eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
   

